[build]
builder = "docker"
dockerfilePath = "bolt.new-any-llm/Dockerfile"

[deploy]
startCommand = "node ./build/server/index.js --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numReplicas = 1

[variables]
NODE_ENV = "production"
